server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/seata_order
    username: test
    password: 1qazXSW@

feign:
  hystrix:
    enabled: false

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 20000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 20000

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: my_test_tx_group
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      server-addr: localhost
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: ${spring.application.name}
#      server-addr: localhost
#      namespace:
#      username: "nacos"
#      password: "nacos"